language: node_js
os: osx
node_js: "8"
install:
  - npm install
  - npm install -g gulp-cli
  - npm install -g vsce
script:
  - vsce package
  - npm run integrationTest
cache:
  directories:
    - "node_modules"
env: CODE_TESTS_PATH=/Users/travis/build/Microsoft/vscode-appcenter/integrationTest CODE_TESTS_WORKSPACE=/Users/travis/build/Microsoft/vscode-appcenter/integrationTest/reactNativeApp