/*
 * Code generated by Microsoft (R) SwaggerTools.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

/* jshint latedef:false */
/* jshint forin:false */
/* jshint noempty:false */

'use strict';

const AppCenterClientCredentials = require('./appCenterClientCredentials');
const Account = require('./account/accountClient');
const Analytics = require('./analytics/analyticsClient');
const Distribute = require('./distribute/distributeClient');
const Build = require('./build/buildClient');
const Crash = require('./crash/crashClient');
const Codepush = require('./codepush/codepushClient');
const Test = require('./test/testClient');
const Export = require('./export/exportClient');
const Push = require('./push/pushClient');


class AppCenterClient {
    constructor(credentials, options = {}) {
        let credentialsObject;
        if (typeof(credentials) === 'string') {
            credentialsObject = new AppCenterClientCredentials(credentials);
        } else if (credentials instanceof AppCenterClientCredentials) {
            credentialsObject = credentials;
        } else {
            throw new Error('Credentials is not a token or credentials object');
        }
        
        this.account = new Account(credentialsObject, null, options);
        
        this.analytics = new Analytics(credentialsObject, null, options);
        
        this.distribute = new Distribute(credentialsObject, null, options);
        
        this.build = new Build(credentialsObject, null, options);
        
        this.crash = new Crash(credentialsObject, null, options);
        
        this.codepush = new Codepush(credentialsObject, null, options);
        
        this.test = new Test(credentialsObject, null, options);
        
        this.export = new Export(credentialsObject, null, options);
        
        this.push = new Push(credentialsObject, null, options);
        
    }
}

module.exports = AppCenterClient;